FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["AG.CLINICAL.Jobs.Web/AG.CLINICAL.Jobs.Web.csproj", "AG.CLINICAL.Jobs.Web/"]
COPY ["AG.CLINICAL.Application/AG.CLINICAL.Application.csproj", "AG.CLINICAL.Application/"]
COPY ["AG.CLINICAL.Domain/AG.CLINICAL.Domain.csproj", "AG.CLINICAL.Domain/"]
COPY ["AG.CLINICAL.Infra.Data/AG.CLINICAL.Infra.Data.csproj", "AG.CLINICAL.Infra.Data/"]
COPY ["AG.CLINICAL.Infra.ExternalApis/AG.CLINICAL.Infra.ExternalApis.csproj", "AG.CLINICAL.Infra.ExternalApis/"]

RUN dotnet restore "AG.CLINICAL.Jobs.Web/AG.CLINICAL.Jobs.Web.csproj"

COPY . .

RUN dotnet publish "AG.CLINICAL.Jobs.Web/AG.CLINICAL.Jobs.Web.csproj" \
    -c Release \
    -o /app/publish \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "AG.CLINICAL.Jobs.Web.dll"]