// <auto-generated />
using System;
using BGD.CLINICAL.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BGD.CLINICAL.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621165858_InitialClinicalSchema")]
    partial class InitialClinicalSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.AplicacaoPaciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompraPacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("compra_paciente_id");

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_aplicacao");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("peso");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("QuantidadeUtilizada")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantidade_utilizada");

                    b.Property<bool>("Realizado")
                        .HasColumnType("boolean")
                        .HasColumnName("realizado");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.HasKey("Id")
                        .HasName("pk_aplicacoes_paciente");

                    b.HasIndex("CompraPacienteId")
                        .HasDatabaseName("ix_aplicacoes_paciente_compra_paciente_id");

                    b.HasIndex("FuncionarioId")
                        .HasDatabaseName("ix_aplicacoes_paciente_funcionario_id");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("ix_aplicacoes_paciente_paciente_id");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_aplicacoes_paciente_produto_id");

                    b.HasIndex("UnidadeId")
                        .HasDatabaseName("ix_aplicacoes_paciente_unidade_id");

                    b.HasIndex("EmpresaId", "PacienteId", "DataAplicacao")
                        .HasDatabaseName("ix_aplicacoes_paciente_empresa_id_paciente_id_data_aplicacao");

                    b.ToTable("aplicacoes_paciente");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.AplicacaoSintoma", b =>
                {
                    b.Property<Guid>("AplicacaoPacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("aplicacao_paciente_id");

                    b.Property<Guid>("SintomaId")
                        .HasColumnType("uuid")
                        .HasColumnName("sintoma_id");

                    b.HasKey("AplicacaoPacienteId", "SintomaId")
                        .HasName("pk_aplicacoes_sintomas");

                    b.HasIndex("SintomaId")
                        .HasDatabaseName("ix_aplicacoes_sintomas_sintoma_id");

                    b.ToTable("aplicacoes_sintomas");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_cargos");

                    b.HasIndex("EmpresaId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_cargos_empresa_id_nome");

                    b.ToTable("cargos");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.CompraPaciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_compra");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<Guid>("PacoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("pacote_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.HasKey("Id")
                        .HasName("pk_compras_paciente");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("ix_compras_paciente_paciente_id");

                    b.HasIndex("PacoteId")
                        .HasDatabaseName("ix_compras_paciente_pacote_id");

                    b.HasIndex("UnidadeId")
                        .HasDatabaseName("ix_compras_paciente_unidade_id");

                    b.HasIndex("EmpresaId", "PacienteId", "Status")
                        .HasDatabaseName("ix_compras_paciente_empresa_id_paciente_id_status");

                    b.ToTable("compras_paciente");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.ContaReceber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompraPacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("compra_paciente_id");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_contas_receber");

                    b.HasIndex("CompraPacienteId")
                        .HasDatabaseName("ix_contas_receber_compra_paciente_id");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("ix_contas_receber_paciente_id");

                    b.HasIndex("EmpresaId", "PacienteId", "Status")
                        .HasDatabaseName("ix_contas_receber_empresa_id_paciente_id_status");

                    b.ToTable("contas_receber");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CorPrincipal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cor_principal");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.HasIndex("Cnpj")
                        .HasDatabaseName("ix_empresas_cnpj");

                    b.ToTable("empresas");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.FormaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_formas_pagamento");

                    b.HasIndex("EmpresaId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_formas_pagamento_empresa_id_nome");

                    b.ToTable("formas_pagamento");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_fornecedores");

                    b.HasIndex("EmpresaId", "Cnpj")
                        .HasDatabaseName("ix_fornecedores_empresa_id_cnpj");

                    b.ToTable("fornecedores");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid?>("CargoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cargo_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("FlagAplicador")
                        .HasColumnType("boolean")
                        .HasColumnName("flag_aplicador");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_funcionarios");

                    b.HasIndex("CargoId")
                        .HasDatabaseName("ix_funcionarios_cargo_id");

                    b.HasIndex("EmpresaId", "Nome")
                        .HasDatabaseName("ix_funcionarios_empresa_id_nome");

                    b.ToTable("funcionarios");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.ItemPacote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PacoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("pacote_id");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("QuantidadeTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantidade_total");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unidade_medida");

                    b.HasKey("Id")
                        .HasName("pk_itens_pacote");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_itens_pacote_produto_id");

                    b.HasIndex("PacoteId", "ProdutoId")
                        .IsUnique()
                        .HasDatabaseName("ix_itens_pacote_pacote_id_produto_id");

                    b.ToTable("itens_pacote");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.ItemPedidoFornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PedidoFornecedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_fornecedor_id");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id")
                        .HasName("pk_itens_pedido_fornecedor");

                    b.HasIndex("PedidoFornecedorId")
                        .HasDatabaseName("ix_itens_pedido_fornecedor_pedido_fornecedor_id");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_itens_pedido_fornecedor_produto_id");

                    b.ToTable("itens_pedido_fornecedor");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.LicencaModulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("ModuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("modulo_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_licencas_modulo");

                    b.HasIndex("ModuloId")
                        .HasDatabaseName("ix_licencas_modulo_modulo_id");

                    b.HasIndex("EmpresaId", "ModuloId")
                        .IsUnique()
                        .HasDatabaseName("ix_licencas_modulo_empresa_id_modulo_id");

                    b.ToTable("licencas_modulo");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.ModuloSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_modulos_sistema");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_modulos_sistema_codigo");

                    b.ToTable("modulos_sistema");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AplicacaoPacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("aplicacao_paciente_id");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid?>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("origem");

                    b.Property<Guid?>("PedidoFornecedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_fornecedor_id");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantidade");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.HasKey("Id")
                        .HasName("pk_movimentacoes_estoque");

                    b.HasIndex("AplicacaoPacienteId")
                        .HasDatabaseName("ix_movimentacoes_estoque_aplicacao_paciente_id");

                    b.HasIndex("FuncionarioId")
                        .HasDatabaseName("ix_movimentacoes_estoque_funcionario_id");

                    b.HasIndex("PedidoFornecedorId")
                        .HasDatabaseName("ix_movimentacoes_estoque_pedido_fornecedor_id");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_movimentacoes_estoque_produto_id");

                    b.HasIndex("UnidadeId")
                        .HasDatabaseName("ix_movimentacoes_estoque_unidade_id");

                    b.HasIndex("EmpresaId", "UnidadeId", "ProdutoId", "Data")
                        .HasDatabaseName("ix_movimentacoes_estoque_empresa_id_unidade_id_produto_id_data");

                    b.ToTable("movimentacoes_estoque");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cpf")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cpf");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.HasKey("Id")
                        .HasName("pk_pacientes");

                    b.HasIndex("UnidadeId")
                        .HasDatabaseName("ix_pacientes_unidade_id");

                    b.HasIndex("EmpresaId", "Cpf")
                        .HasDatabaseName("ix_pacientes_empresa_id_cpf");

                    b.ToTable("pacientes");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Pacote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome");

                    b.Property<int>("QuantidadeAplicacoes")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_aplicacoes");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_pacotes");

                    b.HasIndex("EmpresaId", "Nome")
                        .HasDatabaseName("ix_pacotes_empresa_id_nome");

                    b.ToTable("pacotes");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.PagamentoPaciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContaReceberId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_receber_id");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("FormaPagamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("forma_pagamento_id");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_pagamentos_paciente");

                    b.HasIndex("ContaReceberId")
                        .HasDatabaseName("ix_pagamentos_paciente_conta_receber_id");

                    b.HasIndex("FormaPagamentoId")
                        .HasDatabaseName("ix_pagamentos_paciente_forma_pagamento_id");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("ix_pagamentos_paciente_paciente_id");

                    b.HasIndex("EmpresaId", "PacienteId", "DataPagamento")
                        .HasDatabaseName("ix_pagamentos_paciente_empresa_id_paciente_id_data_pagamento");

                    b.ToTable("pagamentos_paciente");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.PedidoFornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pedido");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("TipoPedido")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo_pedido");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.HasKey("Id")
                        .HasName("pk_pedidos_fornecedor");

                    b.HasIndex("FornecedorId")
                        .HasDatabaseName("ix_pedidos_fornecedor_fornecedor_id");

                    b.HasIndex("UnidadeId")
                        .HasDatabaseName("ix_pedidos_fornecedor_unidade_id");

                    b.HasIndex("EmpresaId", "Status")
                        .HasDatabaseName("ix_pedidos_fornecedor_empresa_id_status");

                    b.ToTable("pedidos_fornecedor");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.PermissaoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Criar")
                        .HasColumnType("boolean")
                        .HasColumnName("criar");

                    b.Property<bool>("Editar")
                        .HasColumnType("boolean")
                        .HasColumnName("editar");

                    b.Property<bool>("Excluir")
                        .HasColumnType("boolean")
                        .HasColumnName("excluir");

                    b.Property<Guid>("ModuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("modulo_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<bool>("Visualizar")
                        .HasColumnType("boolean")
                        .HasColumnName("visualizar");

                    b.HasKey("Id")
                        .HasName("pk_permissoes_usuario");

                    b.HasIndex("ModuloId")
                        .HasDatabaseName("ix_permissoes_usuario_modulo_id");

                    b.HasIndex("UsuarioId", "ModuloId")
                        .IsUnique()
                        .HasDatabaseName("ix_permissoes_usuario_usuario_id_modulo_id");

                    b.ToTable("permissoes_usuario");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<decimal>("EstoqueMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("estoque_minimo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unidade_medida");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("EmpresaId", "Nome")
                        .HasDatabaseName("ix_produtos_empresa_id_nome");

                    b.ToTable("produtos");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Sintoma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_sintomas");

                    b.HasIndex("EmpresaId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_sintomas_empresa_id_nome");

                    b.ToTable("sintomas");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Unidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_unidades");

                    b.HasIndex("EmpresaId", "Nome")
                        .HasDatabaseName("ix_unidades_empresa_id_nome");

                    b.ToTable("unidades");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid?>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("FuncionarioId")
                        .HasDatabaseName("ix_usuarios_funcionario_id");

                    b.HasIndex("EmpresaId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_empresa_id_email");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.AplicacaoPaciente", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.CompraPaciente", "CompraPaciente")
                        .WithMany("Aplicacoes")
                        .HasForeignKey("CompraPacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_aplicacoes_paciente_compras_paciente_compra_paciente_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_aplicacoes_paciente_empresas_empresa_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_aplicacoes_paciente_funcionarios_funcionario_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Aplicacoes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_aplicacoes_paciente_pacientes_paciente_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_aplicacoes_paciente_produtos_produto_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_aplicacoes_paciente_unidades_unidade_id");

                    b.Navigation("CompraPaciente");

                    b.Navigation("Empresa");

                    b.Navigation("Funcionario");

                    b.Navigation("Paciente");

                    b.Navigation("Produto");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.AplicacaoSintoma", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.AplicacaoPaciente", "AplicacaoPaciente")
                        .WithMany("Sintomas")
                        .HasForeignKey("AplicacaoPacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_aplicacoes_sintomas_aplicacoes_paciente_aplicacao_paciente_~");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Sintoma", "Sintoma")
                        .WithMany("Aplicacoes")
                        .HasForeignKey("SintomaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_aplicacoes_sintomas_sintomas_sintoma_id");

                    b.Navigation("AplicacaoPaciente");

                    b.Navigation("Sintoma");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Cargo", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Cargos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cargos_empresas_empresa_id");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.CompraPaciente", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compras_paciente_empresas_empresa_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Compras")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compras_paciente_pacientes_paciente_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Pacote", "Pacote")
                        .WithMany("Compras")
                        .HasForeignKey("PacoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compras_paciente_pacotes_pacote_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compras_paciente_unidades_unidade_id");

                    b.Navigation("Empresa");

                    b.Navigation("Paciente");

                    b.Navigation("Pacote");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.ContaReceber", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.CompraPaciente", "CompraPaciente")
                        .WithMany()
                        .HasForeignKey("CompraPacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contas_receber_compras_paciente_compra_paciente_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contas_receber_empresas_empresa_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contas_receber_pacientes_paciente_id");

                    b.Navigation("CompraPaciente");

                    b.Navigation("Empresa");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.FormaPagamento", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_formas_pagamento_empresas_empresa_id");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Fornecedor", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fornecedores_empresas_empresa_id");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Funcionario", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.Cargo", "Cargo")
                        .WithMany("Funcionarios")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_funcionarios_cargos_cargo_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Funcionarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_funcionarios_empresas_empresa_id");

                    b.Navigation("Cargo");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.ItemPacote", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.Pacote", "Pacote")
                        .WithMany("Itens")
                        .HasForeignKey("PacoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itens_pacote_pacotes_pacote_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itens_pacote_produtos_produto_id");

                    b.Navigation("Pacote");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.ItemPedidoFornecedor", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.PedidoFornecedor", "PedidoFornecedor")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoFornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itens_pedido_fornecedor_pedidos_fornecedor_pedido_fornecedor~");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itens_pedido_fornecedor_produtos_produto_id");

                    b.Navigation("PedidoFornecedor");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.LicencaModulo", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany("LicencasModulo")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_licencas_modulo_empresas_empresa_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.ModuloSistema", "Modulo")
                        .WithMany("Licencas")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_licencas_modulo_modulos_sistema_modulo_id");

                    b.Navigation("Empresa");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.AplicacaoPaciente", "AplicacaoPaciente")
                        .WithMany("MovimentacoesEstoque")
                        .HasForeignKey("AplicacaoPacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movimentacoes_estoque_aplicacoes_paciente_aplicacao_pacient~");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_estoque_empresas_empresa_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movimentacoes_estoque_funcionarios_funcionario_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.PedidoFornecedor", "PedidoFornecedor")
                        .WithMany()
                        .HasForeignKey("PedidoFornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movimentacoes_estoque_pedidos_fornecedor_pedido_fornecedor_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_estoque_produtos_produto_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_estoque_unidades_unidade_id");

                    b.Navigation("AplicacaoPaciente");

                    b.Navigation("Empresa");

                    b.Navigation("Funcionario");

                    b.Navigation("PedidoFornecedor");

                    b.Navigation("Produto");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pacientes_empresas_empresa_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pacientes_unidades_unidade_id");

                    b.Navigation("Empresa");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Pacote", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pacotes_empresas_empresa_id");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.PagamentoPaciente", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.ContaReceber", "ContaReceber")
                        .WithMany("Pagamentos")
                        .HasForeignKey("ContaReceberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagamentos_paciente_contas_receber_conta_receber_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagamentos_paciente_empresas_empresa_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.FormaPagamento", "FormaPagamento")
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagamentos_paciente_formas_pagamento_forma_pagamento_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagamentos_paciente_pacientes_paciente_id");

                    b.Navigation("ContaReceber");

                    b.Navigation("Empresa");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.PedidoFornecedor", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_fornecedor_empresas_empresa_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany("Pedidos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_fornecedor_fornecedores_fornecedor_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_fornecedor_unidades_unidade_id");

                    b.Navigation("Empresa");

                    b.Navigation("Fornecedor");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.PermissaoUsuario", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.ModuloSistema", "Modulo")
                        .WithMany("PermissoesUsuario")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_permissoes_usuario_modulos_sistema_modulo_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Permissoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_permissoes_usuario_usuarios_usuario_id");

                    b.Navigation("Modulo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Produto", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_produtos_empresas_empresa_id");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Sintoma", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sintomas_empresas_empresa_id");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Unidade", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Unidades")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_unidades_empresas_empresa_id");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("BGD.CLINICAL.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_empresas_empresa_id");

                    b.HasOne("BGD.CLINICAL.Domain.Entities.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_usuarios_funcionarios_funcionario_id");

                    b.Navigation("Empresa");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.AplicacaoPaciente", b =>
                {
                    b.Navigation("MovimentacoesEstoque");

                    b.Navigation("Sintomas");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Cargo", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.CompraPaciente", b =>
                {
                    b.Navigation("Aplicacoes");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.ContaReceber", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("Funcionarios");

                    b.Navigation("LicencasModulo");

                    b.Navigation("Unidades");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Fornecedor", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.ModuloSistema", b =>
                {
                    b.Navigation("Licencas");

                    b.Navigation("PermissoesUsuario");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Aplicacoes");

                    b.Navigation("Compras");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Pacote", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.PedidoFornecedor", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Sintoma", b =>
                {
                    b.Navigation("Aplicacoes");
                });

            modelBuilder.Entity("BGD.CLINICAL.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Permissoes");
                });
#pragma warning restore 612, 618
        }
    }
}
